version: "1.0"
services:
    broker:
        container_name: "rabbitmq-switchdin"
        environment:
            - RABBITMQ_DEFAULT_USER="mqtt-test"
            - RABBITMQ_DEFAULT_PASS="mqtt-test"
        build: Dockerfile.broker
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
            # MQTT plugin port
            - '1883:1883'


    app1:
        container_name: "app1"
        build: Dockerfile.app1
        
    app2:
        container_name: "app2"
        build: Dockerfile.app2
    
    app3:
        container_name: "app3"
        build: Dockerfile.app3