name: flake8-check
run-name: flake8-check

on: 
  pull_request:
    paths:
      - '**.py'
jobs:
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt

      - name: Install flake8
        run: |
          pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          # exclude: ""
          max-line-length: "79"
          path: "."
          plugins: "flake8-bugbear==22.1.11 flake8-black"
